# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            EdNui
tagline:          Everday Nuisances
url:              https://zommuter.github.io
paginate:         1
baseurl:          /EdNui/
author:
  name:           Tobias Kienzler
  url:            https://zommuter.github.io
  email:          zommuter@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/zommuter/EdNui.git
